version: "3"
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./server:/var/www/
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laravel
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d